<?php
return [
	APP_NS.'\Globals\Traits'    => APP_PATH . '/Globals/Traits',
	APP_NS.'\Globals\Plugins'    => APP_PATH . '/Globals/Plugins',
	APP_NS.'\Globals\Bases'    => APP_PATH . '/Globals/Bases',
	APP_NS.'\Globals\Finals'    => APP_PATH . '/Globals/Finals',
	APP_NS.'\Tables\Transport'    => APP_PATH . '/Tables/Transport',
	APP_NS.'\Tables\Area'    => APP_PATH . '/Tables/Area',
	APP_NS.'\Tables\Brand'    => APP_PATH . '/Tables/Brand',
	APP_NS.'\Tables'    => APP_PATH . '/Tables',
	APP_NS.'\Tables\User'    => APP_PATH . '/Tables/User',
	APP_NS.'\Tables\Manager'    => APP_PATH . '/Tables/Manager',
	APP_NS.'\Tables\Goods'    => APP_PATH . '/Tables/Goods',
	APP_NS.'\Tables\Warehouse'    => APP_PATH . '/Tables/Warehouse',
	APP_NS.'\Tables\Stock'    => APP_PATH . '/Tables/Stock',
	APP_NS.'\Tables\Grant'    => APP_PATH . '/Tables/Grant',
	APP_NS.'\Network\Common'    => APP_PATH . '/Network/Common',
	APP_NS.'\Network\Modules'    => APP_PATH . '/Network/Modules',
	APP_NS.'\Network\Modules\Frontend\Plugins'    => APP_PATH . '/Network/Modules/Frontend/Plugins',
	APP_NS.'\Network\Modules\Frontend\Common'    => APP_PATH . '/Network/Modules/Frontend/Common',
	APP_NS.'\Network\Modules\Frontend'    => APP_PATH . '/Network/Modules/Frontend',
	APP_NS.'\Network\Modules\Frontend\Controllers'    => APP_PATH . '/Network/Modules/Frontend/Controllers',
	APP_NS.'\Network\Modules\Manager\Plugins'    => APP_PATH . '/Network/Modules/Manager/Plugins',
	APP_NS.'\Network\Modules\Manager\Common'    => APP_PATH . '/Network/Modules/Manager/Common',
	APP_NS.'\Network\Modules\Manager'    => APP_PATH . '/Network/Modules/Manager',
	APP_NS.'\Network\Modules\Manager\Controllers'    => APP_PATH . '/Network/Modules/Manager/Controllers',
	APP_NS.'\Helpers'    => APP_PATH . '/Helpers',
	APP_NS.'\Console\Common'    => APP_PATH . '/Console/Common',
	APP_NS.'\Console\Modules'    => APP_PATH . '/Console/Modules',
	APP_NS.'\Console\Modules\Mission\Tasks'    => APP_PATH . '/Console/Modules/Mission/Tasks',
	APP_NS.'\Console\Modules\Mission\Common'    => APP_PATH . '/Console/Modules/Mission/Common',
	APP_NS.'\Console\Modules\Mission'    => APP_PATH . '/Console/Modules/Mission',
];